rpm: fix %if syntax
rpm in fedora-33 complains about not quoted strings:

    error: bare words are no longer supported, please use "...":  xxen == xxen

(cherry picked from commit a40344252a82976677fc0df5eb97a1a88cfdf74a)