tests/vm/dispvm: skip broken test_002_template_change
After adding the missing run_until_complete() calls, it fails with:

ERROR: qubes.tests.vm.dispvm/TC_00_DispVM/test_002_template_change
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/devel/github/qubes-core-admin/qubes/tests/__init__.py", line 398, in wrapper
    func(*args, **kwargs)
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/user/devel/github/qubes-core-admin/qubes/tests/vm/dispvm.py", line 119, in test_002_template_change
    self.loop.run_until_complete(self.dispvm.start())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/devel/github/qubes-core-admin/qubes/vm/dispvm.py", line 242, in start
    await super().start(**kwargs)
  File "/home/user/devel/github/qubes-core-admin/qubes/vm/qubesvm.py", line 1119, in start
    raise qubes.exc.QubesVMNotFoundError(self.name)
qubes.exc.QubesVMNotFoundError: No such domain: 'test-dispvm'

(cherry picked from commit b85c90d781dad790c42d293e9b391382aa0e8b26)